# -*- coding: utf-8 -*-
"""day 21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VhdEnxpTuTSkzxeuXPUVh0WPNGCAKUsu
"""

#BIVARIENT ANALYSIS and multi varient analysis ( analysis of 2 or more than 2 coloumns together)
import pandas as pd
import seaborn as sns

tips=sns.load_dataset('tips')

tips.head()

titanic=pd.read_csv('train.csv')   # icouldnot do this using sns.load_datset('') bcz it would not request to this developers who created the seaborn library but in the others we use those names whose click the users who created so thats why i couldnot do this here with train like sns.load_datset('train')

titanic

flights=sns.load_dataset('flights')

flights

iris=sns.load_dataset('iris')

iris

from matplotlib import defaultParams
#NUMERICAL NUMERICAL  (SACTTER PLOT AND LINE PLOT AT THE BELOW)
#scatter plot   # in scatte ploy y is depenedent and x is indepenednet and hue is the categorical coloumn also add style and size parameter
#sns.scatterplot(x=tips['total_bill'],y=tips['tip']) #its a numerical to numerical bivarient analysis  # linear relationships between the tip and total bill if bill is greater so tip sis also greater in most of the cases
#sns.scatterplot(x=tips['total_bill'],y=tips['tip'],hue=tips['sex']) #its a numerical to numerical multivarient
sns.scatterplot(x=tips['total_bill'],y=tips['tip'],hue=tips['sex'],style=tips['day'],size=tips['time'])
# its a multivarient analysis between tital bill tips sex smoker nd size num of family persons

#BAR PLOT (NUMERICAL AND CATEGORICAL)  # in bar plot we dont have size and style we have x y hue hue_order
titanic.head()

sns.barplot(x=titanic['Pclass'],y=titanic['Age']) #bivarient analysis its shows that in Pclass 3 younger and in Pclass 1 older age is travellig the middle line is the confidence support which shows that if there arr 5 popel so asking their age so their is more accuracy so least error line of confience suport is lower if line is greater so the confieence support is higher more chances of accuracy bcz more porple like 1000 so chnace of erorr are high high confidenc support high line

#sns.barplot(x=titanic['Pclass'],y=titanic['Age'],hue=titanic['Sex'])   # multi varient analysis barchrt only 3 paraemter are used
#now i want to add the 4th parameter so which i have to use catplot
#x: Horizontal groups.

#y: Numerical value.

#hue: Color-coded sub-groups.

#col: Creates a new column of charts for another category.

#row: Creates a new row of charts for a fifth category.

sns.catplot(x=titanic['Pclass'],y=titanic['Age'],hue=titanic['Sex'],col=titanic['Survived'],row=titanic['Embarked'])

#DISTPLOT   is used for numerical colomn
sns.distplot(titanic[titanic['Survived'] == 0]['Age'],hist=False)  # the prople who died
sns.distplot(titanic[titanic['Survived']==1]['Age'],hist=False)    #graph shows the survival rate of child orange is higher than the died rate but in old age the surival age is lower

titanic.head(3)

#CATEGORICAL TO CATEGORICAL    HEATMAP
sns.heatmap(pd.crosstab(titanic['Pclass'], titanic['Survived']))

titanic.groupby('Embarked')['Survived'].mean() * 100
#titanic.groupby('Pclass')['Survived'].mean() * 100
#(titanic.groupby('Pclass')['Survived'].mean() * 100).plot(kind='bar')

#CLUSTER MAP (CATEGORICAL AND CATEGORICAL)
sns.clustermap(pd.crosstab(titanic['SibSp'],titanic['Survived']))

#PAIR PLOT ()
iris.head()

sns.pairplot(iris,hue='species')

#LINE PLOT (NUMERICAL TO NUMERICAL)
#if quantity in x axis is time based
flights.head()

new=flights.groupby('year').sum(numeric_only=True).reset_index()

sns.lineplot(x=new['year'],y=new['passengers'])  #on x axis we passed line baed quantity that is year

flights.pivot_table(values='passengers',index='month',columns='year')

sns.heatmap(flights.pivot_table(values='passengers',index='month',columns='year'))  # when you havr to do anlaysis of too many nmers or quanities so yo hvae to use heatmap
# we get understanid after nalysisng the heat map that when year inc so the no of passengers increases and in summmer months like jun july and august more passengers travel

sns.clustermap(flights.pivot_table(values='passengers',index='month',columns='year'))   # it kept all the quantities of same behaviour together

