# -*- coding: utf-8 -*-
"""day 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17F7F5__UdHHiYq2FGcCagtYAKUjjEHdt
"""

import pandas as pd
import requests

#fetch by using api
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=e7e9dd2aa2baebc22993fc851f98d1e8&language=en-US&page=1')

#just get desired items
pd.DataFrame(response.json()['results']).head(2)[['id','title','overview','popularity','release_date','vote_average','vote_count']]

df=pd.DataFrame()
df

#making data frame for each page in a loop and then combine all the data frames to make a big dataframe of 8000+ movies
for i in range(1,521):
  response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=e7e9dd2aa2baebc22993fc851f98d1e8&language=en-US&page={}'.format(i))
  temp_dataframe=pd.DataFrame(response.json()['results']).head(2)[['id','title','overview','popularity','release_date','vote_average','vote_count']]
  df = pd.concat([df, temp_dataframe], ignore_index=True)  #ignore indexing

df.shape

movies.to_csv('movies.csv')