# -*- coding: utf-8 -*-
"""day 15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gL3C_OBDxigrlRcdy-xLeAOd18Y2kccx
"""

import pandas as pd

#want to getdat from any csv file
df=pd.read_csv('/content/CSV.csv')

df

#if you want to load by using link
import pandas as pd

# CSV file link
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv"

# Read CSV data directly from the URL
data = pd.read_csv(url)

# Display first few rows
print(data.head())

pd.read_csv('/content/student_data.tsv',sep='\t')
#\t for run the tsv file

#coloumn names when are not defined
pd.read_csv('/content/noColoumn.csv', sep=',', names=['Names','Age','Grade','City'])

#to get just specific coloumns
pd.read_csv('/content/CSV.csv', usecols=['Country Name','Country Code','1967','2011','2023'])

#skip the rows
pd.read_csv('/content/noColoumn.csv',skiprows=[1,2])

#according to our own get no of rows
pd.read_csv('/content/CSV.csv',nrows=36)

# it will handle the special correct as well without showing error it convert the character into utf-8 for encoding
pd.read_csv('/content/special_characters.csv',encoding='latin-1')

pd.read_csv('/content/skip.csv')

#for skipping  bad lines
pd.read_csv('/content/skip.csv', sep=',', encoding="latin-1", on_bad_lines='skip')

#pd.read_csv('/content/date.csv').info()   # treat as object
pd.read_csv('/content/date.csv',parse_dates=['date']).info()   # now treat as date

#for renaming any field
def rename(name):
  if name == "Ayesha":
    return "jeeni"
  else:
    return name

rename("Ayesha")

pd.read_csv("/content/date.csv",converters={'Name' :rename})

a = pd.read_csv('/content/CSV.csv',chunksize=100)

for chunks in a:
  print(chunks.shape)